---
- name: Create base directories
  file:
    state: directory
    follow: true
    path: "{{ item.dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0777
  with_items:
    - dir: "{{ root_dir }}"
    - dir: "{{ config_dir }}"
    - dir: "{{ product_log_dir }}"
    - dir: "{{ bin_dir }}"
    - dir: "{{ cache_dir }}"
    - dir: "{{ src_dir }}"
      include: "{{ is_cloud }}"
  when: item.include|default(true)|bool
