---
- name: Create django ansible_settings.py
  template:
    src: "{{ playbook_dir }}/templates/django/ansible_settings.py.j2"
    dest: "{{ ansible_settings_py }}"
    owner: "{{ vbox_user if is_vbox else nginx_user }}"
    group: "{{ vbox_group if is_vbox else nginx_group }}"
    mode: "{{ '0o666' if is_vbox else '0o655' }}"
