---
- hosts: todo
  become: true

  vars:
    product: "django-drf-jwt-ansible-todo"
    sub_product: "todo"

  vars_files:
    - "../../group_vars/base"
    - "../../group_vars/todo"

  roles:
    - role: base
      logs:
        - file: "{{ log }}"
    - role: gitlab
      repositories:
        - "{{ product }}"
    - role: pip
      dirs:
        - "{{ app_dir }}"
    - role: ANXS.postgresql
      when: not_prd|bool
    - role: DavidWittman.redis
      when: not_prd|bool
    - role: geerlingguy.supervisor
    - role: jdauphant.nginx
    - role: geerlingguy.nodejs
    - role: django
    - role: supervisor
      templates:
        - "gunicorn"
    - role: done
